excluded:
  - Model/SQLite/**

disabled_rules:
    - attributes
    - line_length
    - file_length
    - function_body_length
    - trailing_whitespace
    - todo
    - identifier_name
    - generic_type_name
    - type_name
    - number_separator
    - void_function_in_ternary
    - function_parameter_count
    - blanket_disable_command
    - cyclomatic_complexity
    - empty_enum_arguments
    - discouraged_object_literal

#identifier_name:
#  max_length:
#    warning: 55
#    error: 60
#  excluded:
#    - x
#    - y
#    - a
#    - r
#    - g
#    - b
#    - id
#    - CS
    
nesting:
    type_level: 2
    warning: 2
    error: 6
    function_level: 3
    warning: 5
    error: 10
    
analyzer_rules:
    - unused_declaration
    - unused_import
    - explicit_self
    - capture_variable
  
opt_in_rules:
  - file_header
  - array_init
  - balanced_xctest_lifecycle
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_string
  - enum_case_associated_values_count
  - expiring_todo
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - legacy_random
  - literal_expression_end_indentation
  - missing_docs
  - modifier_order
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - raw_value_for_camel_cased_codable_enum
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

file_header:
    required_pattern: |
        \/\/
        \/\/  .*?\.swift
        \/\/  .*?
        \/\/
        \/\/  Created by .*? on \d{1,2}\/\d{1,2}\/\d{4}\.
        \/\/  Copyright © \d{4} NetTrinity\. All rights reserved\.
        \/\/
